# Generated by Django 4.1.7 on 2023-05-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0002_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='name',
            new_name='username',
        ),
    ]
